language: node_js
node_js:
- '12'
warnings_are_errors: false
env:
  global:
  - secure: FBzCZWAKYsFmeGlTDPgbiwKTmiYfv9Rq9gnsaVHc6Tesh0rF9fzngicK00OpxPyrWVbk+sUwbd5/GB1jVA0rtfbgV/n+wSlvBxIUhsR2M4Q5pqBALBvWssVZwgjNCh3ZXBRlyrtyp9WlO8e9Q0tQhOQsdIfsDA7G/aP10bby1Jn2gKSL6EemWITWjo2uIqfgDi0nADrUWLtjyDn/jswy6OtD0MnZZwkumK1mlZB8deofiW+fD2LcbL0hdhZkJRhcaLFSwv8zxAZVrJqAGLUeqZRZdKuKpt/RKB4b5hL1/5U3Xz97p6XOc/bEHsc2fkfSN5oZzY/KtL58o0Ed/bfWDj1Wa9LRRQQFXjab5hTWYI1QZzNo5DRXZ+wiie4b7kJkCXFJTNFLNCb5FBFs3XYpu6kFjody+qNGwfqutnGdWoKU1/ysJsM7JjOhA9gsSVnkpirDdmDyGtuwPw2ex3IZ2yPYSwfYZS8gSbna+a0Y1b4nBMH+N+gJha76gSK8ctP2IHxCYRqnTRpCkeq7VCZsEqKThcBWquI0arMneFEcr++sSIYf0xie8CkbEXE+RQj0Dp8mahqzvOlhczZCJ4Q++jmbMX1XhgN6+aVvvC1faHMwCPC3rPv6J1z2RwwowEyRI6uNsJxfcOK3YXwKxi3xQpFvYVP3xkYDwUJFwP6teZ0=
  - secure: rOVKlNxduNDshMwUpUIu7DfJiXBZRJYJcMH3eOLzJ7He+IYfGWfj9pA/mIBOStyXOCKmUR21pVO2UWv+rA2C3yyZd9j9mNc1248FVhozGh/Mi6Y7I55TIewLJZ9RW9vjCN4LX4Xt2kwSpZUfaV7/fhEVFJXBnm43Vqy1oEc5/paWtP2vk3RS5lze2hI/OCQsGtqKWShMC600fLfN34aYPyKMTv/aMmV3mCkxCjREpHdNFrMUG8pxFFWMSc6klfEt1GXdfIG6X2VXvbXiUqEuzTwu+u+srn/Np7ruQSNIEZy7/r/tgE2MQ+/TZNO2OpQq8QR/yb7TkPpUDUBCccGgaf0+gWe6+V5Se+aFyVl5zfmEKf+z4psUlxbtuwanGpb4NAYpnTt9WEjOmiEqm68LQ3K9dIpkOq4RQ6Fr8STfT4swU5g9L3vNGN6pXOQTk5RFAAETY4a11scxZFwT6412eOnLx7ZM9i5Nu9gyiT3I5nghz0/MxPsFNzN1JOiHLoT+QKK47pcbjH3e39I61D81RGQDVulsST+pJCQZn6HuEOILFeeP0IirRZOQu/1ALuSCutm9MZHF8ZSPhzB/laGmG4bT1R9ueavA1yOfJTv1vHHPLahhD8kYaFiRcT9+cpYIKsnVWa6/zAl+SRzKohsoTw/hmgitt80U8mkW2jOcIUU=
  - secure: VUGQVtGBn4xa0qJpzkfefiO3i89DtHTlb0NwhAu8DNmJ8+KYvbZ85iSnr1JShRor2D7PFUQchETq4dBn1ra8Gl+r+rV2fuPopof4HoT5xat9HKp2+RSmZY3aufqHnfDsi8RWzNzbwSxiPToqaEsCwuEBIk30wg0oNwyF4J+xUR8HA9OmTCdvFoD/rbhUyM9QppwgkqaHllKzLX9H+TOqHI058alBlcoAx+0eqna4vmSFaQa7V28n//fTlhw3Uvb5Qwz+QSz1IDqjfQnLGlzX2Ag9d8LA9CtZ+arQdJXICUKwGj/XBic4MYGGOKjDvw6ruvRyurP56ofPhFw6hFp315QZao319gGLfHQJx4ktwQllr1EKHB0k+DbZ3FKFzWj9zJBabYhQlevHIKmVGCRDHS08v7F9itJiBx9qeOt9jAm/49B8pYXUbbju7vM0K8Wjk+hqJm/guI+01FnrGjfamDuWOvH6KxBxmW+ukhPSzvFUAB39a/xQMyE/zOVMYP8SrShZz3kHht3mqzFK0RO+NqC/lG79S15ReMzId5hz1jhjPee2yMNE/Jk2kEf8ewC/N/NjHQ2NFs+MUW4EOahEq+ZxkxCX2KvmIB76m3Cs1iKPTxLE6rQZzYIFyFkDPqTiI0zIePDjKFNDnMMb6QRbC+bT8odKN+mClMimOpZdRsA=
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  local_dir: build
  region: ap-southeast-1
  on: master
