language: node_js
node_js:
- '12'
warnings_are_errors: false
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: roydenrego.com
  skip_cleanup: true
  local_dir: build
  region: ap-southeast-1
  on: master
