language: node_js
node_js:
- '12'
warnings_are_errors: false
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- npm run build
deploy:
  provider: s3
  access_key_id:
    secure: e+OT2Bi4FBgv20Q9x6O0Uimpsm9dPe9QwMLMv5UGeSkGBgEjjphCoMaETZePgU+7VjYINcXrgrRtwEfEyicSZ4a16uJBVfCgaANEHvIBG3AZcwLv0Tm0vrrSqFcUgwIbtlw6DkKXDNSiDRzLpxO2EKm+7kHAyGHWOaOt8RlKoof2kDO7GLgPwRF1UUR71kUDxktzaS4O7raJU8z4nKhlb6N+Qu4g39pNrQt1UB7QOyc0RQEZBfswO6QdCzjXCKV/t4wdv+69sdhf1mySsRG/9paVYnTAMBz9krlpp1Yit+taVCzsiAxsMSekBQ+69wvbOUKTsyoIrHPGl5FeThw/CQrobS9nde3M+ViER2ad9SzvDQMY7MgxxR2uq6rtzyLo/hkJZB2dj2uUwmRPmTGYesCR+Ch9PyZ1HdpjbLYT9kacbvaVZxv6wjd+fKTkQu3qLt1sghr5Lr5bIjBWlm2jgaYCppA3/VXLZJOCBLSgwqiPe3CzPlDoD6dfMqHuU6FowgqngsXfIL9SpD1jKPBbul6mWYmYVQHVk9ZN8p5nFgJjF1yn4CEDFKuGet6FptYsRQ5MnWz9KSnG59iSOI+yZfq/pMmwUOS0LKFkGZj6wQtjKHjth0eEdWU8U7tspkkutOJGZG8CAfd/+OQojKZuMYGN1Upsbk0AGtFYkEGymJw=
  secret_access_key:
    secure: WuFaLzhkkXFOCzFdygmUlM+iMokqMov3lpkUxzOKEk+usREV+gM3CIAHMhFp7WLzBKjtzwmZGOw39Dd1VwgG4XGINsF1Mm9jCQ1LatiGM1Kf6m6X6/9KgrGLdTJ5mE0NWrw0t8SGT65w3LvzjWcxJTf8wS4Ixup9iV+ZpDPApJLHa7hPbc6UO42hI85blwGLyi+MciM/b8emelQ+aYnU/ELHdTDGzBey435wJDONz1LTy++WheUBomOYFAjPJxe/qAKNgPXK1DIZPypdoV7uBeEuTlbP6eb3anW/k5YBrNJfj5JIBGFBuuQnTVRrXHb48l55GZ2mQtU/XdIMYklQv9mtbAmzH1S29oyhjJb1waoSpPstXfFcnFXF+lJvX50hqx9vcrgoUXm2Wt/7hf7rpbHXFF63B0rHzxUVHE/zbFrbcIV5YQtfaX+UA9R8vPwyncv2kh6nxx6vXes6eE6lU0FdUIr1eJw9eMryEkk6Tm1b79P2EBc/J3+VBWo0eVs4ZpvWgCXu+y97cHLlhMFszPONXaF/8pVufoPAeiQGptGGb0lL7CYMXY94kAh/icXojKloreUN2AN6aRQwRWhHAhf/ubXAo6H98GZ7znILiXXagE0EMTf13dlTwQg0g9n2u7dxHv67i4pjYqrjTvkVMjlt2x80B1lop9dpaynZprg=
  bucket: roydenrego.com
  skip_cleanup: true
  local_dir: build
  region: ap-southeast-1
  on: master
